### PR TITLE
Update server.R (unknown aesthetics text warning)

### PR DESCRIPTION
**Pull request by twinklevatwani**
Removed 'text' aesthetic from geom_bar in manpower tab to fix warnings.

### CODE REVIEW

**Comment by twinklevatwani** [comment]
Removed 'text' aesthetic from geom_bar in manpower tab to fix warnings.

**Review by sanjmeh — COMMENTED** [review]
Can you apply this fix to the next plot too (Pilferage tab)?

**Comment by twinklevatwani** [comment]
Sure sir, doing it

**Comment by twinklevatwani** [comment]
I have done the changes sir.

**Pull request merged**
