### PR TITLE
server.R

### PR DESCRIPTION
**Pull request by twinklevatwani**
Handle Empty Value in "Number of shifts"

Add input validation using `req()` for key numeric inputs to prevent missing value errors

### CODE REVIEW

**Comment by bkowshik** [comment]
Thank you for this PR @twinklevatwani Can you please resolve the conflicts and update the PR.

**Comment by twinklevatwani** [comment]
Hello Bhargav,

I have updated the PR by solving the conflicts.
Requesting you to kindly check my pull request

I have attempted to resolve three issues.

- Handling empty value in “Number of shifts”.  Using req() statement.
- consistently style all “ Info” boxes with green background using
“btn-info” class.
- removing spelling mistakes using hunspell package in R.

Thank you,
Twinkle Vatwani

**Comment by sanjmeh** [comment]
I still see conflicts @twinklevatwani

**Comment by twinklevatwani** [comment]
I have combined everything into one req().
Kindly check.

**Review by sanjmeh — APPROVED** [review]

**Pull request merged**
