### PR TITLE
Update and rename ui.R to ui.R

### PR DESCRIPTION
**Pull request by twinklevatwani**
Added rentals tab UI with input fields and dynamic savings charts

### CODE REVIEW

**Comment by sanjmeh** [comment]
why have you renamed the ui.R ? @twinklevatwani 
Screenshot 2024-12-18 at 10 19 55 AM

**Comment by sanjmeh** [comment]
Also your PR does not have any code changes to server.R. To make the rental tab work you need server code also. And please donot rename any file, as these (ui.R and server.R) are names enforced in shiny architecture.
@twinklevatwani

**Comment by twinklevatwani** [comment]
I have renamed to orginal name.

**Comment by twinklevatwani** [comment]
I have added the calculation of rentals in server.r code and sent a pull request.

**Pull request closed without merging**
